<?php

namespace Modules\Dummy\Database\Seeders\Modules\Inventory\Versions\V2_3_0;

use Illuminate\Database\Seeder;

class LocationsTableSeeder extends Seeder
{
    public function run()
    {
        if (\DB::table('locations')->count() == 0) {
            \DB::table('locations')->delete();
        }

        \DB::table('locations')->insert([
            0 => [
                'id' => 1,
                'shop_id' => 2,
                'vendor_id' => 1,
                'name' => 'Gadgets',
                'slug' => 'gadgets',
                'address' => 'Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            1 => [
                'id' => 2,
                'shop_id' => 7,
                'vendor_id' => 16,
                'name' => 'Furniture',
                'slug' => 'furniture',
                'address' => 'House no 12, Road no 21,Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            2 => [
                'id' => 3,
                'shop_id' => 5,
                'vendor_id' => 19,
                'name' => 'Clothes',
                'slug' => 'clothes',
                'address' => 'House no 19, Road no 2, Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            3 => [
                'id' => 4,
                'shop_id' => 2,
                'vendor_id' => 1,
                'name' => 'Organic',
                'slug' => 'organic',
                'address' => 'Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 0,
            ],
            4 => [
                'id' => 5,
                'shop_id' => 2,
                'vendor_id' => 1,
                'name' => 'Gadgets-2',
                'slug' => 'gadgets-2',
                'address' => 'Dhaka, Gazipur, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 0,
            ],
            5 => [
                'id' => 6,
                'shop_id' => 2,
                'vendor_id' => 1,
                'name' => 'Foods',
                'slug' => 'food',
                'address' => 'Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Inactive',
                'is_default' => 0,
            ],
            6 => [
                'id' => 7,
                'shop_id' => 7,
                'vendor_id' => 16,
                'name' => 'Furniture-2',
                'slug' => 'furniture-2',
                'address' => 'Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 0,
            ],
            7 => [
                'id' => 8,
                'shop_id' => 1,
                'vendor_id' => 2,
                'name' => 'Dhaka',
                'slug' => 'dhaka',
                'address' => 'Dhaka, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            8 => [
                'id' => 9,
                'shop_id' => 3,
                'vendor_id' => 17,
                'name' => 'Chittagong',
                'slug' => 'chittagong',
                'address' => 'Chittagong, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            9 => [
                'id' => 10,
                'shop_id' => 4,
                'vendor_id' => 18,
                'name' => 'Khulna',
                'slug' => 'khulna',
                'address' => 'Khulna, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            10 => [
                'id' => 11,
                'shop_id' => 5,
                'vendor_id' => 19,
                'name' => 'Rajshahi',
                'slug' => 'rajshahi',
                'address' => 'Rajshahi, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 0,
            ],
            11 => [
                'id' => 12,
                'shop_id' => 6,
                'vendor_id' => 20,
                'name' => 'Sylhet',
                'slug' => 'sylhet',
                'address' => 'Sylhet, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            12 => [
                'id' => 13,
                'shop_id' => 8,
                'vendor_id' => 21,
                'name' => 'Barisal',
                'slug' => 'barisal',
                'address' => 'Barisal, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            13 => [
                'id' => 14,
                'shop_id' => 9,
                'vendor_id' => 22,
                'name' => 'Rangpur',
                'slug' => 'rangpur',
                'address' => 'Rangpur, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            14 => [
                'id' => 15,
                'shop_id' => 10,
                'vendor_id' => 23,
                'name' => 'Mymensingh',
                'slug' => 'mymensingh',
                'address' => 'Mymensingh, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            15 => [
                'id' => 16,
                'shop_id' => 11,
                'vendor_id' => 24,
                'name' => 'Dinajpur',
                'slug' => 'dinajpur',
                'address' => 'Dinajpur, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
            16 => [
                'id' => 17,
                'shop_id' => 12,
                'vendor_id' => 25,
                'name' => 'Gazipur',
                'slug' => 'gazipur',
                'address' => 'Gazipur, Bangladesh',
                'country' => 'bd',
                'status' => 'Active',
                'is_default' => 1,
            ],
        ]);
    }
}
